### ISSUE TITLE
Can't inject session

### ISSUE THREAD

**Issue by diogolast** [NavpreetDevpuri/share-web-whatsapp#4]
Does whatsapp changed something? I am not able to inject the session. I keep stuck on QR Code page.

**Comment by NavpreetDevpuri** [comment]
As far as I know, they changed something related with multi device support that effects our session hijacking method, need to investigate further.

**Comment by NavpreetDevpuri** [comment]
Try to use [Tithiwa](https://github.com/Tithibots/tithiwa).

**Comment by diogolast** [comment]
@NavpreetDevpuri thanks for answering, I will try.
